const currencies = [
  { code: "USD", label: "US Dollar", symbol: "$" },
  { code: "EUR", label: "Euro", symbol: "€" },
  { code: "GBP", label: "British Pound", symbol: "£" },
  { code: "JPY", label: "Japanese Yen", symbol: "¥" },
  { code: "CAD", label: "Canadian Dollar", symbol: "CA$" },
  { code: "AUD", label: "Australian Dollar", symbol: "A$" },
  { code: "CHF", label: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", label: "Chinese Yuan", symbol: "元" },
  { code: "HKD", label: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NZD", label: "New Zealand Dollar", symbol: "NZ$" },
  { code: "SEK", label: "Swedish Krona", symbol: "kr" },
  { code: "KRW", label: "South Korean Won", symbol: "₩" },
  { code: "SGD", label: "Singapore Dollar", symbol: "S$" },
  { code: "INR", label: "Indian Rupee", symbol: "₹" },
  { code: "MXN", label: "Mexican Peso", symbol: "Mex$" },
  { code: "BRL", label: "Brazilian Real", symbol: "R$" },
  { code: "ZAR", label: "South African Rand", symbol: "R" },
  { code: "RUB", label: "Russian Ruble", symbol: "₽" },
  { code: "TRY", label: "Turkish Lira", symbol: "₺" },
  { code: "PLN", label: "Polish Zloty", symbol: "zł" },
  { code: "MGA", label: "Malagasy Ariary", symbol: "Ar" },
  { code: "CLP", label: "Chilean Peso", symbol: "Ch$" },
  { code: "MUR", label: "Mauritian Rupee", symbol: "Rs" },
];
export default currencies;
